import { Module } from '@nestjs/common';
import { ScheduleModule } from '@nestjs/schedule';
import { DataTransferController } from './data-transfer.controller';
import { DataTransferService } from './data-transfer.service';
import {
  CsvParserService,
  FileStorageService,
  ImportJobService,
  ImportProcessorService,
  ExportService,
} from './services';
import {
  IMPORT_STRATEGIES,
  UserImportStrategy,
  TenantImportStrategy,
  ModuleItemProgressImportStrategy,
  RAW_IMPORT_STRATEGIES,
  TenantRawImportStrategy,
  UserRawImportStrategy,
  CategoryRawImportStrategy,
  CourseRawImportStrategy,
  BatchRawImportStrategy,
  ApplicationRawImportStrategy,
  SupportedLanguageRawImportStrategy,
  StudentIdCounterRawImportStrategy,
  ActivityTypeRawImportStrategy,
  ModuleRawImportStrategy,
  ModuleItemRawImportStrategy,
  LessonContentRawImportStrategy,
  QuizContentRawImportStrategy,
  AssignmentContentRawImportStrategy,
  QuizQuestionRawImportStrategy,
  QuizOptionRawImportStrategy,
  PrerequisiteRawImportStrategy,
  ResourceRawImportStrategy,
  ModuleItemProgressRawImportStrategy,
} from './strategies';
import { CleanupService } from './cleanup.service';

@Module({
  imports: [ScheduleModule.forRoot()],
  controllers: [DataTransferController],
  providers: [
    DataTransferService,
    CsvParserService,
    FileStorageService,
    ImportJobService,
    ImportProcessorService,
    ExportService,
    CleanupService,
    // Import strategies
    UserImportStrategy,
    TenantImportStrategy,
    ModuleItemProgressImportStrategy,
    {
      provide: IMPORT_STRATEGIES,
      useFactory: (
        userStrategy: UserImportStrategy,
        tenantStrategy: TenantImportStrategy,
        moduleItemProgressStrategy: ModuleItemProgressImportStrategy,
      ) => [userStrategy, tenantStrategy, moduleItemProgressStrategy],
      inject: [UserImportStrategy, TenantImportStrategy, ModuleItemProgressImportStrategy],
    },
    // Raw import strategies
    SupportedLanguageRawImportStrategy,
    TenantRawImportStrategy,
    UserRawImportStrategy,
    CategoryRawImportStrategy,
    CourseRawImportStrategy,
    BatchRawImportStrategy,
    ApplicationRawImportStrategy,
    StudentIdCounterRawImportStrategy,
    ActivityTypeRawImportStrategy,
    ModuleRawImportStrategy,
    ModuleItemRawImportStrategy,
    LessonContentRawImportStrategy,
    QuizContentRawImportStrategy,
    AssignmentContentRawImportStrategy,
    QuizQuestionRawImportStrategy,
    QuizOptionRawImportStrategy,
    PrerequisiteRawImportStrategy,
    ResourceRawImportStrategy,
    ModuleItemProgressRawImportStrategy,
    {
      provide: RAW_IMPORT_STRATEGIES,
      useFactory: (
        supportedLanguageRaw: SupportedLanguageRawImportStrategy,
        tenantRaw: TenantRawImportStrategy,
        userRaw: UserRawImportStrategy,
        categoryRaw: CategoryRawImportStrategy,
        courseRaw: CourseRawImportStrategy,
        batchRaw: BatchRawImportStrategy,
        applicationRaw: ApplicationRawImportStrategy,
        studentIdCounterRaw: StudentIdCounterRawImportStrategy,
        activityTypeRaw: ActivityTypeRawImportStrategy,
        moduleRaw: ModuleRawImportStrategy,
        moduleItemRaw: ModuleItemRawImportStrategy,
        lessonContentRaw: LessonContentRawImportStrategy,
        quizContentRaw: QuizContentRawImportStrategy,
        assignmentContentRaw: AssignmentContentRawImportStrategy,
        quizQuestionRaw: QuizQuestionRawImportStrategy,
        quizOptionRaw: QuizOptionRawImportStrategy,
        prerequisiteRaw: PrerequisiteRawImportStrategy,
        resourceRaw: ResourceRawImportStrategy,
        moduleItemProgressRaw: ModuleItemProgressRawImportStrategy,
      ) => [
        supportedLanguageRaw,
        tenantRaw,
        userRaw,
        categoryRaw,
        courseRaw,
        batchRaw,
        applicationRaw,
        studentIdCounterRaw,
        activityTypeRaw,
        moduleRaw,
        moduleItemRaw,
        lessonContentRaw,
        quizContentRaw,
        assignmentContentRaw,
        quizQuestionRaw,
        quizOptionRaw,
        prerequisiteRaw,
        resourceRaw,
        moduleItemProgressRaw,
      ],
      inject: [
        SupportedLanguageRawImportStrategy,
        TenantRawImportStrategy,
        UserRawImportStrategy,
        CategoryRawImportStrategy,
        CourseRawImportStrategy,
        BatchRawImportStrategy,
        ApplicationRawImportStrategy,
        StudentIdCounterRawImportStrategy,
        ActivityTypeRawImportStrategy,
        ModuleRawImportStrategy,
        ModuleItemRawImportStrategy,
        LessonContentRawImportStrategy,
        QuizContentRawImportStrategy,
        AssignmentContentRawImportStrategy,
        QuizQuestionRawImportStrategy,
        QuizOptionRawImportStrategy,
        PrerequisiteRawImportStrategy,
        ResourceRawImportStrategy,
        ModuleItemProgressRawImportStrategy,
      ],
    },
  ],
  exports: [DataTransferService, CsvParserService, TenantRawImportStrategy, UserRawImportStrategy],
})
export class DataTransferModule {}
