import { ImportEntityType } from '@/common/enums/import-entity-type.enum';
import { StrategyConfig } from '../strategies/base-raw-import.strategy';

export const STRATEGY_CONFIGS: Record<
  string,
  { config: StrategyConfig; sampleRow: Record<string, string> }
> = {
  [ImportEntityType.TENANT]: {
    config: {
      entityType: ImportEntityType.TENANT,
      dependencyOrder: 0,
      prismaModel: 'tenant',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'name', prismaField: 'name', type: 'string', required: true },
        { name: 'slug', prismaField: 'slug', type: 'string', required: true },
        { name: 'alias', prismaField: 'alias', type: 'string' },
        { name: 'logoUrl', prismaField: 'logoUrl', type: 'string' },
        { name: 'primaryColor', prismaField: 'primaryColor', type: 'string' },
        { name: 'secondaryColor', prismaField: 'secondaryColor', type: 'string' },
        { name: 'contactEmail', prismaField: 'contactEmail', type: 'string', required: true },
        { name: 'contactPhone', prismaField: 'contactPhone', type: 'string' },
        { name: 'address', prismaField: 'address', type: 'json' },
        { name: 'website', prismaField: 'website', type: 'string' },
        { name: 'defaultLanguageCode', prismaField: 'defaultLanguageCode', type: 'string' },
        { name: 'enabledLanguages', prismaField: 'enabledLanguages', type: 'json' }, // Array of strings
        { name: 'timezone', prismaField: 'timezone', type: 'string' },
        { name: 'isActive', prismaField: 'isActive', type: 'boolean', defaultValue: true },
        { name: 'settings', prismaField: 'settings', type: 'json' },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: [],
    },
    sampleRow: {
      id: 'TNT_abc123',
      name: '{"en":"Acme Corp","ar":"شركة أكمي"}',
      slug: 'acme-corp',
      contactEmail: 'admin@acme.com',
      isActive: 'true',
    },
  },
  [ImportEntityType.USER]: {
    config: {
      entityType: ImportEntityType.USER,
      dependencyOrder: 1,
      prismaModel: 'user',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'email', prismaField: 'email', type: 'string', required: true },
        { name: 'firstName', prismaField: 'firstName', type: 'json', required: true },
        { name: 'lastName', prismaField: 'lastName', type: 'json', required: true },
        { name: 'role', prismaField: 'role', type: 'string', required: true },
        { name: 'passwordHash', prismaField: 'passwordHash', type: 'string' },
        { name: 'phone', prismaField: 'phone', type: 'string' },
        { name: 'avatarUrl', prismaField: 'avatarUrl', type: 'string' },
        {
          name: 'emailVerified',
          prismaField: 'emailVerified',
          type: 'boolean',
          defaultValue: false,
        },
        { name: 'emailVerifiedAt', prismaField: 'emailVerifiedAt', type: 'date' },
        { name: 'verificationToken', prismaField: 'verificationToken', type: 'string' },
        {
          name: 'verificationTokenExpires',
          prismaField: 'verificationTokenExpires',
          type: 'date',
        },
        { name: 'passwordResetToken', prismaField: 'passwordResetToken', type: 'string' },
        { name: 'passwordResetExpires', prismaField: 'passwordResetExpires', type: 'date' },
        { name: 'preferredLanguageCode', prismaField: 'preferredLanguageCode', type: 'string' },
        { name: 'lastLoginAt', prismaField: 'lastLoginAt', type: 'date' },
        { name: 'isActive', prismaField: 'isActive', type: 'boolean', defaultValue: true },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['tenantId'],
    },
    sampleRow: {
      id: 'USR_abc123',
      tenantId: 'TNT_xyz789',
      email: 'user@example.com',
      firstName: '{"en":"John","ar":"جون"}',
      lastName: '{"en":"Doe","ar":"دو"}',
      role: 'applicant',
      isActive: 'true',
    },
  },
  [ImportEntityType.CATEGORY]: {
    config: {
      entityType: ImportEntityType.CATEGORY,
      dependencyOrder: 2,
      prismaModel: 'category',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'name', prismaField: 'name', type: 'json', required: true },
        { name: 'description', prismaField: 'description', type: 'json' },
        { name: 'slug', prismaField: 'slug', type: 'string', required: true },
        { name: 'isActive', prismaField: 'isActive', type: 'boolean', defaultValue: true },
        { name: 'sortOrder', prismaField: 'sortOrder', type: 'number', defaultValue: 0 },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['tenantId'],
    },
    sampleRow: {
      id: 'CAT_abc123',
      tenantId: 'TNT_xyz789',
      slug: 'tech',
      name: '{"en":"Technology","ar":"تكنولوجيا"}',
      isActive: 'true',
    },
  },
  [ImportEntityType.COURSE]: {
    config: {
      entityType: ImportEntityType.COURSE,
      dependencyOrder: 3,
      prismaModel: 'course',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'title', prismaField: 'title', type: 'json', required: true },
        { name: 'description', prismaField: 'description', type: 'json' },
        { name: 'shortDescription', prismaField: 'shortDescription', type: 'json' },
        { name: 'thumbnailUrl', prismaField: 'thumbnailUrl', type: 'string' },
        { name: 'categoryId', prismaField: 'categoryId', type: 'string', required: true },
        { name: 'level', prismaField: 'level', type: 'string' },
        { name: 'prerequisites', prismaField: 'prerequisites', type: 'json' },
        { name: 'learningOutcomes', prismaField: 'learningOutcomes', type: 'json' },
        { name: 'requiredDocuments', prismaField: 'requiredDocuments', type: 'json' },
        { name: 'isPublished', prismaField: 'isPublished', type: 'boolean', defaultValue: false },
        { name: 'isFeatured', prismaField: 'isFeatured', type: 'boolean', defaultValue: false },
        { name: 'isActive', prismaField: 'isActive', type: 'boolean', defaultValue: true },
        { name: 'sortOrder', prismaField: 'sortOrder', type: 'number', defaultValue: 0 },
        { name: 'code', prismaField: 'code', type: 'string' },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['tenantId', 'categoryId'],
    },
    sampleRow: {
      id: 'CRS_abc123',
      tenantId: 'TNT_xyz789',
      categoryId: 'CAT_def456',
      code: 'CS101',
      title: '{"en":"Intro to CS","ar":"مقدمة في علوم الحاسب"}',
      isPublished: 'true',
    },
  },
  [ImportEntityType.BATCH]: {
    config: {
      entityType: ImportEntityType.BATCH,
      dependencyOrder: 3,
      prismaModel: 'batch',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'courseId', prismaField: 'courseId', type: 'string', required: true },
        { name: 'name', prismaField: 'name', type: 'json', required: true },
        { name: 'code', prismaField: 'code', type: 'string', required: true },
        { name: 'batchNumber', prismaField: 'batchNumber', type: 'string', required: true },
        {
          name: 'enrollmentStartDate',
          prismaField: 'enrollmentStartDate',
          type: 'date',
          required: true,
        },
        {
          name: 'enrollmentEndDate',
          prismaField: 'enrollmentEndDate',
          type: 'date',
          required: true,
        },
        { name: 'startDate', prismaField: 'startDate', type: 'date', required: true },
        { name: 'endDate', prismaField: 'endDate', type: 'date', required: true },
        { name: 'maxStudents', prismaField: 'maxStudents', type: 'number', required: true },
        { name: 'isActive', prismaField: 'isActive', type: 'boolean', defaultValue: true },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['tenantId', 'courseId'],
    },
    sampleRow: {
      id: 'BAT_abc123',
      tenantId: 'TNT_xyz789',
      courseId: 'CRS_def456',
      name: '{"en":"Fall 2025","ar":"خريف 2025"}',
      code: 'BATCH-001',
      startDate: '2025-01-01',
      endDate: '2025-06-30',
    },
  },
  [ImportEntityType.APPLICATION]: {
    config: {
      entityType: ImportEntityType.APPLICATION,
      dependencyOrder: 4,
      prismaModel: 'application',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'batchId', prismaField: 'batchId', type: 'string', required: true },
        { name: 'courseId', prismaField: 'courseId', type: 'string', required: true },
        { name: 'applicantId', prismaField: 'applicantId', type: 'string', required: true },
        {
          name: 'applicationNumber',
          prismaField: 'applicationNumber',
          type: 'string',
          required: true,
        },
        { name: 'rollNumber', prismaField: 'rollNumber', type: 'string' },
        { name: 'personalInfo', prismaField: 'personalInfo', type: 'json' },
        { name: 'guardianInfo', prismaField: 'guardianInfo', type: 'json' },
        { name: 'educationInfo', prismaField: 'educationInfo', type: 'json' },
        { name: 'status', prismaField: 'status', type: 'string', defaultValue: 'draft' },
        { name: 'submittedAt', prismaField: 'submittedAt', type: 'date' },
        { name: 'reviewedBy', prismaField: 'reviewedBy', type: 'string' },
        { name: 'reviewedAt', prismaField: 'reviewedAt', type: 'date' },
        { name: 'reviewNotes', prismaField: 'reviewNotes', type: 'string' },
        { name: 'rejectionReason', prismaField: 'rejectionReason', type: 'json' },
        { name: 'ipAddress', prismaField: 'ipAddress', type: 'string' },
        { name: 'userAgent', prismaField: 'userAgent', type: 'string' },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['batchId', 'courseId', 'applicantId'],
    },
    sampleRow: {
      id: 'APP_abc123',
      tenantId: 'TNT_xyz789',
      batchId: 'BAT_def456',
      courseId: 'CRS_ghi789',
      applicantId: 'USR_jkl012',
      applicationNumber: 'APP-2025-001',
      status: 'draft',
    },
  },
  [ImportEntityType.SUPPORTED_LANGUAGE]: {
    config: {
      entityType: ImportEntityType.SUPPORTED_LANGUAGE,
      dependencyOrder: 0,
      prismaModel: 'supportedLanguage',
      primaryKeyField: 'code', // Custom PK
      fields: [
        { name: 'code', prismaField: 'code', type: 'string', required: true },
        { name: 'name', prismaField: 'name', type: 'string', required: true },
        { name: 'nativeName', prismaField: 'nativeName', type: 'string', required: true },
        { name: 'direction', prismaField: 'direction', type: 'string', defaultValue: 'ltr' },
        { name: 'isActive', prismaField: 'isActive', type: 'boolean', defaultValue: true },
        { name: 'isDefault', prismaField: 'isDefault', type: 'boolean', defaultValue: false },
      ],
      foreignKeyFields: [],
    },
    sampleRow: {
      code: 'en',
      name: 'English',
      nativeName: 'English',
      direction: 'ltr',
      isDefault: 'true',
    },
  },
  [ImportEntityType.STUDENT_ID_COUNTER]: {
    config: {
      entityType: ImportEntityType.STUDENT_ID_COUNTER,
      dependencyOrder: 1,
      prismaModel: 'studentIdCounter',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'contextKey', prismaField: 'contextKey', type: 'string', required: true },
        { name: 'currentCount', prismaField: 'currentCount', type: 'number', required: true },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
      ],
      foreignKeyFields: [],
    },
    sampleRow: {
      id: 'SIC_abc123',
      tenantId: 'TNT_xyz789',
      contextKey: 'STU-AM-CS101-BATCH001',
      currentCount: '100',
    },
  },
  [ImportEntityType.ACTIVITY_TYPE]: {
    config: {
      entityType: ImportEntityType.ACTIVITY_TYPE,
      dependencyOrder: 1,
      prismaModel: 'activityType',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'code', prismaField: 'code', type: 'string', required: true },
        { name: 'title', prismaField: 'title', type: 'json', required: true },
        { name: 'description', prismaField: 'description', type: 'json' },
        { name: 'isActive', prismaField: 'isActive', type: 'boolean', defaultValue: true },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['tenantId'],
    },
    sampleRow: {
      id: 'AT_abc123',
      tenantId: 'TNT_xyz789',
      code: 'lesson',
      title: '{"en":"Lesson","ar":"درس"}',
      isActive: 'true',
    },
  },
  [ImportEntityType.MODULE]: {
    config: {
      entityType: ImportEntityType.MODULE,
      dependencyOrder: 4, // Depends on Course
      prismaModel: 'module',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'courseId', prismaField: 'courseId', type: 'string', required: true },
        { name: 'title', prismaField: 'title', type: 'json', required: true },
        { name: 'description', prismaField: 'description', type: 'json' },
        { name: 'order', prismaField: 'sortOrder', type: 'number', required: true },
        { name: 'isPublished', prismaField: 'isPublished', type: 'boolean', defaultValue: false },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['tenantId', 'courseId'],
    },
    sampleRow: {
      id: 'MOD_abc123',
      tenantId: 'TNT_xyz789',
      courseId: 'CRS_def456',
      title: '{"en":"Introduction","ar":"مقدمة"}',
      sortOrder: '1',
    },
  },
  [ImportEntityType.MODULE_ITEM]: {
    config: {
      entityType: ImportEntityType.MODULE_ITEM,
      dependencyOrder: 5, // Depends on Module, ActivityType
      prismaModel: 'moduleItem',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'moduleId', prismaField: 'moduleId', type: 'string', required: true },
        { name: 'activityTypeId', prismaField: 'activityTypeId', type: 'string', required: true },
        { name: 'title', prismaField: 'title', type: 'json', required: true },
        { name: 'description', prismaField: 'description', type: 'json' },
        { name: 'sortOrder', prismaField: 'sortOrder', type: 'number', required: true },
        { name: 'completionRules', prismaField: 'completionRules', type: 'json' },
        { name: 'isPublished', prismaField: 'isPublished', type: 'boolean', defaultValue: false },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['tenantId', 'moduleId', 'activityTypeId'],
    },
    sampleRow: {
      id: 'MI_abc123',
      tenantId: 'TNT_xyz789',
      moduleId: 'MOD_def456',
      activityTypeId: 'AT_ghi789',
      title: '{"en":"First Lesson","ar":"الدرس الأول"}',
      sortOrder: '1',
    },
  },
  [ImportEntityType.LESSON_CONTENT]: {
    config: {
      entityType: ImportEntityType.LESSON_CONTENT,
      dependencyOrder: 6, // Depends on ModuleItem
      prismaModel: 'lessonContent',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'moduleItemId', prismaField: 'moduleItemId', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'videoUrl', prismaField: 'videoUrl', type: 'string' },
        { name: 'title', prismaField: 'title', type: 'json' },
        { name: 'thumbnailUrl', prismaField: 'thumbnailUrl', type: 'string' },
        { name: 'description', prismaField: 'description', type: 'json' },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['moduleItemId', 'tenantId'],
    },
    sampleRow: {
      id: 'LC_abc123',
      moduleItemId: 'MI_def456',
      tenantId: 'TNT_xyz789',
      videoUrl: 'https://example.com/video.mp4',
      title: '{"en":"Lesson Title","ar":"عنوان الدرس"}',
    },
  },
  [ImportEntityType.QUIZ_CONTENT]: {
    config: {
      entityType: ImportEntityType.QUIZ_CONTENT,
      dependencyOrder: 6, // Depends on ModuleItem
      prismaModel: 'quizContent',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'moduleItemId', prismaField: 'moduleItemId', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'passingScore', prismaField: 'passingScore', type: 'number' },
        { name: 'timeLimitMinutes', prismaField: 'timeLimitMinutes', type: 'number' },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['moduleItemId', 'tenantId'],
    },
    sampleRow: {
      id: 'QC_abc123',
      moduleItemId: 'MI_def456',
      tenantId: 'TNT_xyz789',
      passingScore: '50',
      timeLimitMinutes: '30',
    },
  },
  [ImportEntityType.ASSIGNMENT_CONTENT]: {
    config: {
      entityType: ImportEntityType.ASSIGNMENT_CONTENT,
      dependencyOrder: 6, // Depends on ModuleItem
      prismaModel: 'assignmentContent',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'moduleItemId', prismaField: 'moduleItemId', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'instructions', prismaField: 'instructions', type: 'json' },
        { name: 'dueDate', prismaField: 'dueDate', type: 'date' },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['moduleItemId', 'tenantId'],
    },
    sampleRow: {
      id: 'AC_abc123',
      moduleItemId: 'MI_def456',
      tenantId: 'TNT_xyz789',
      instructions: '{"en":"Submit by Friday","ar":"تسليم يوم الجمعة"}',
      dueDate: '2025-12-31',
    },
  },
  [ImportEntityType.QUIZ_QUESTION]: {
    config: {
      entityType: ImportEntityType.QUIZ_QUESTION,
      dependencyOrder: 7, // Depends on QuizContent
      prismaModel: 'quizQuestion',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'quizId', prismaField: 'quizId', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'questionText', prismaField: 'questionText', type: 'json', required: true },
        { name: 'questionType', prismaField: 'questionType', type: 'string', required: true },
        { name: 'sortOrder', prismaField: 'sortOrder', type: 'number', required: true },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['quizId', 'tenantId'],
    },
    sampleRow: {
      id: 'QQ_abc123',
      quizId: 'QC_def456',
      tenantId: 'TNT_xyz789',
      questionText: '{"en":"What is 2+2?","ar":"ما هو ناتج 2+2؟"}',
      questionType: 'multiple_choice',
    },
  },
  [ImportEntityType.QUIZ_OPTION]: {
    config: {
      entityType: ImportEntityType.QUIZ_OPTION,
      dependencyOrder: 8, // Depends on QuizQuestion
      prismaModel: 'quizOption',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'questionId', prismaField: 'questionId', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'optionText', prismaField: 'optionText', type: 'json', required: true },
        { name: 'isCorrect', prismaField: 'isCorrect', type: 'boolean', required: true },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['questionId', 'tenantId'],
    },
    sampleRow: {
      id: 'QO_abc123',
      questionId: 'QQ_def456',
      tenantId: 'TNT_xyz789',
      optionText: '{"en":"4","ar":"4"}',
      isCorrect: 'true',
    },
  },
  [ImportEntityType.PREREQUISITE]: {
    config: {
      entityType: ImportEntityType.PREREQUISITE,
      dependencyOrder: 8, // Depends on ModuleItem
      prismaModel: 'prerequisite',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'moduleItemId', prismaField: 'moduleItemId', type: 'string', required: true },
        {
          name: 'prerequisiteItemId',
          prismaField: 'prerequisiteItemId',
          type: 'string',
          required: true,
        },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
      ],
      foreignKeyFields: ['moduleItemId', 'prerequisiteItemId', 'tenantId'],
    },
    sampleRow: {
      id: 'PR_abc123',
      tenantId: 'TNT_xyz789',
      moduleItemId: 'MI_def456',
      prerequisiteItemId: 'MI_ghi789',
    },
  },
  [ImportEntityType.RESOURCE]: {
    config: {
      entityType: ImportEntityType.RESOURCE,
      dependencyOrder: 8, // Depends on ModuleItem
      prismaModel: 'resource',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'moduleItemId', prismaField: 'moduleItemId', type: 'string', required: true },
        { name: 'title', prismaField: 'title', type: 'json', required: true },
        { name: 'resourceType', prismaField: 'resourceType', type: 'string', required: true },
        { name: 'resourceUrl', prismaField: 'resourceUrl', type: 'string', required: true },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['moduleItemId', 'tenantId'],
    },
    sampleRow: {
      id: 'RES_abc123',
      tenantId: 'TNT_xyz789',
      moduleItemId: 'MI_def456',
      title: '{"en":"Supplementary Material","ar":"مواد إضافية"}',
      resourceType: 'pdf',
      resourceUrl: 'https://example.com/file.pdf',
    },
  },
  [ImportEntityType.MODULE_ITEM_PROGRESS]: {
    config: {
      entityType: ImportEntityType.MODULE_ITEM_PROGRESS,
      dependencyOrder: 9, // Depends on ModuleItem, User
      prismaModel: 'moduleItemProgress',
      fields: [
        { name: 'id', prismaField: 'id', type: 'string', required: true },
        { name: 'tenantId', prismaField: 'tenantId', type: 'string', required: true },
        { name: 'userId', prismaField: 'userId', type: 'string', required: true },
        { name: 'moduleItemId', prismaField: 'moduleItemId', type: 'string', required: true },
        { name: 'status', prismaField: 'status', type: 'string', defaultValue: 'not_started' },
        {
          name: 'progressPercent',
          prismaField: 'progressPercent',
          type: 'number',
          defaultValue: 0,
        },
        { name: 'completedAt', prismaField: 'completedAt', type: 'date' },
        { name: 'createdAt', prismaField: 'createdAt', type: 'date' },
        { name: 'updatedAt', prismaField: 'updatedAt', type: 'date' },
        { name: 'createdBy', prismaField: 'createdBy', type: 'string' },
        { name: 'updatedBy', prismaField: 'updatedBy', type: 'string' },
        { name: 'deletedAt', prismaField: 'deletedAt', type: 'date' },
        { name: 'deletedBy', prismaField: 'deletedBy', type: 'string' },
      ],
      foreignKeyFields: ['tenantId', 'userId', 'moduleItemId'],
    },
    sampleRow: {
      id: 'MIP_abc123',
      tenantId: 'TNT_xyz789',
      userId: 'USR_ghi789',
      moduleItemId: 'MI_def456',
      status: 'completed',
      progressPercent: '100',
    },
  },
};
