export enum ImportEntityType {
  TENANT = 'tenant',
  USER = 'user',
  CATEGORY = 'category',
  COURSE = 'course',
  BATCH = 'batch',
  APPLICATION = 'application',
  STUDENT_ID_COUNTER = 'student_id_counter',
  ACTIVITY_TYPE = 'activity_type',
  MODULE = 'module',
  MODULE_ITEM = 'module_item',
  LESSON_CONTENT = 'lesson_content',
  QUIZ_CONTENT = 'quiz_content',
  QUIZ_QUESTION = 'quiz_question',
  QUIZ_OPTION = 'quiz_option',
  ASSIGNMENT_CONTENT = 'assignment_content',
  PREREQUISITE = 'prerequisite',
  RESOURCE = 'resource',
  SUPPORTED_LANGUAGE = 'supported_language',
  MODULE_ITEM_PROGRESS = 'module_item_progress',
}
