export enum ImportEntityType {
  USER = 'user',
  TENANT = 'tenant',
  MODULE_ITEM_PROGRESS = 'module_item_progress',
  // Raw import types for system-to-system sync
  SUPPORTED_LANGUAGE_RAW = 'supported_language_raw',
  TENANT_RAW = 'tenant_raw',
  USER_RAW = 'user_raw',
  CATEGORY_RAW = 'category_raw',
  COURSE_RAW = 'course_raw',
  BATCH_RAW = 'batch_raw',
  APPLICATION_RAW = 'application_raw',
  STUDENT_ID_COUNTER_RAW = 'student_id_counter_raw',
  ACTIVITY_TYPE_RAW = 'activity_type_raw',
  MODULE_RAW = 'module_raw',
  MODULE_ITEM_RAW = 'module_item_raw',
  LESSON_CONTENT_RAW = 'lesson_content_raw',
  QUIZ_CONTENT_RAW = 'quiz_content_raw',
  ASSIGNMENT_CONTENT_RAW = 'assignment_content_raw',
  QUIZ_QUESTION_RAW = 'quiz_question_raw',
  QUIZ_OPTION_RAW = 'quiz_option_raw',
  PREREQUISITE_RAW = 'prerequisite_raw',
  RESOURCE_RAW = 'resource_raw',
  MODULE_ITEM_PROGRESS_RAW = 'module_item_progress_raw',
}
